language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

matrix:

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - (cd examples/laravel-5 && cp ../../composer.phar . && php composer.phar install)

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - vendor/bin/phpunit
  - (cd examples/laravel-5 && vendor/bin/phpunit)
  - mv composer.json composer.json.orig
  - cp -f composer.json.orig composer.json && rm -f composer.lock && rm -rf vendor && composer require laravel/framework:5.4.* && vendor/bin/phpunit
